-- AlterTable
ALTER TABLE "etapas_tipo" ALTER COLUMN "tipo_iniciativa" SET DEFAULT false,
ALTER COLUMN "tipo_obra" SET DEFAULT false,
ALTER COLUMN "region" SET DEFAULT false,
ALTER COLUMN "provincia" SET DEFAULT false,
ALTER COLUMN "comuna" SET DEFAULT false,
ALTER COLUMN "volumen" SET DEFAULT false,
ALTER COLUMN "presupuesto_oficial" SET DEFAULT false,
ALTER COLUMN "fecha_llamado_licitacion" SET DEFAULT false,
ALTER COLUMN "fecha_recepcion_ofertas_tecnicas" SET DEFAULT false,
ALTER COLUMN "fecha_apertura_ofertas_economicas" SET DEFAULT false,
ALTER COLUMN "fecha_inicio_concesion" SET DEFAULT false,
ALTER COLUMN "decreto_adjudicacion" SET DEFAULT false,
ALTER COLUMN "sociedad_concesionaria" SET DEFAULT false,
ALTER COLUMN "inspector_fiscal_id" SET DEFAULT false,
ALTER COLUMN "plazo_total_concesion" SET DEFAULT false,
ALTER COLUMN "valor_referencia" SET DEFAULT false,
ALTER COLUMN "bip" SET DEFAULT false,
ALTER COLUMN "color" SET DATA TYPE VARCHAR(20);
