apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gestor-backend-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gestor-backend-cluster-rolebinding
subjects:
- kind: User
  name: lfuentes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gestor-backend-cluster-role
  apiGroup: rbac.authorization.k8s.io
