apiVersion: v1
kind: Secret
metadata:
  name: gestor-backend-secrets
type: Opaque
data:
  # These are example values - replace with your actual base64 encoded values
  # To encode: echo -n "your-value" | base64
  database-url: cG9zdGdyZXNxbDovL2FkbWluOmFkbWluQHBvc3RncmVzcWw6NTQzMi9wb3N0Z3Jlcy8=  # postgresql://admin:admin@postgresql:5432/postgres/
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # your-jwt-secret-key-here
  minio-access-key: bWluaW9hZG1pbg==  # minioadmin
  minio-secret-key: bWluaW9hZG1pbg==  # minioadmin
