// scripts/comunas-chile-completas.js
// Array completo de comunas de Chile para usar en el seed.js

const comunasChile = [
    // Región de Arica y Parinacota (XV)
    { nombre: 'Arica', provincia_id: 1, region_id: 1 },
    { nombre: 'Camarones', provincia_id: 1, region_id: 1 },
    { nombre: 'Putre', provincia_id: 2, region_id: 1 },
    { nombre: 'General Lagos', provincia_id: 2, region_id: 1 },
  
    // Región de Tarapacá (I)
    { nombre: 'Iquique', provincia_id: 3, region_id: 2 },
    { nombre: 'Alto Hospicio', provincia_id: 3, region_id: 2 },
    { nombre: 'Pozo Almonte', provincia_id: 4, region_id: 2 },
    { nombre: 'Camiña', provincia_id: 4, region_id: 2 },
    { nombre: 'Colchane', provincia_id: 4, region_id: 2 },
    { nombre: 'Huara', provincia_id: 4, region_id: 2 },
    { nombre: 'Pica', provincia_id: 4, region_id: 2 },
  
    // Región de Antofagasta (II)
    { nombre: 'Antofagasta', provincia_id: 5, region_id: 3 },
    { nombre: 'Mejillones', provincia_id: 5, region_id: 3 },
    { nombre: 'Sierra Gorda', provincia_id: 5, region_id: 3 },
    { nombre: 'Taltal', provincia_id: 5, region_id: 3 },
    { nombre: 'Calama', provincia_id: 6, region_id: 3 },
    { nombre: 'Ollagüe', provincia_id: 6, region_id: 3 },
    { nombre: 'San Pedro de Atacama', provincia_id: 6, region_id: 3 },
    { nombre: 'Tocopilla', provincia_id: 7, region_id: 3 },
    { nombre: 'María Elena', provincia_id: 7, region_id: 3 },
  
    // Región de Atacama (III)
    { nombre: 'Copiapó', provincia_id: 8, region_id: 4 },
    { nombre: 'Caldera', provincia_id: 8, region_id: 4 },
    { nombre: 'Tierra Amarilla', provincia_id: 8, region_id: 4 },
    { nombre: 'Chañaral', provincia_id: 9, region_id: 4 },
    { nombre: 'Diego de Almagro', provincia_id: 9, region_id: 4 },
    { nombre: 'Vallenar', provincia_id: 10, region_id: 4 },
    { nombre: 'Alto del Carmen', provincia_id: 10, region_id: 4 },
    { nombre: 'Freirina', provincia_id: 10, region_id: 4 },
    { nombre: 'Huasco', provincia_id: 10, region_id: 4 },
  
    // Región de Coquimbo (IV)
    { nombre: 'La Serena', provincia_id: 11, region_id: 5 },
    { nombre: 'Coquimbo', provincia_id: 11, region_id: 5 },
    { nombre: 'Andacollo', provincia_id: 11, region_id: 5 },
    { nombre: 'La Higuera', provincia_id: 11, region_id: 5 },
    { nombre: 'Paiguano', provincia_id: 11, region_id: 5 },
    { nombre: 'Vicuña', provincia_id: 11, region_id: 5 },
    { nombre: 'Illapel', provincia_id: 12, region_id: 5 },
    { nombre: 'Canela', provincia_id: 12, region_id: 5 },
    { nombre: 'Los Vilos', provincia_id: 12, region_id: 5 },
    { nombre: 'Salamanca', provincia_id: 12, region_id: 5 },
    { nombre: 'Ovalle', provincia_id: 13, region_id: 5 },
    { nombre: 'Combarbalá', provincia_id: 13, region_id: 5 },
    { nombre: 'Monte Patria', provincia_id: 13, region_id: 5 },
    { nombre: 'Punitaqui', provincia_id: 13, region_id: 5 },
    { nombre: 'Río Hurtado', provincia_id: 13, region_id: 5 },
  
    // Región de Valparaíso (V)
    { nombre: 'Valparaíso', provincia_id: 14, region_id: 6 },
    { nombre: 'Casablanca', provincia_id: 14, region_id: 6 },
    { nombre: 'Concón', provincia_id: 14, region_id: 6 },
    { nombre: 'Juan Fernández', provincia_id: 14, region_id: 6 },
    { nombre: 'Puchuncaví', provincia_id: 14, region_id: 6 },
    { nombre: 'Quintero', provincia_id: 14, region_id: 6 },
    { nombre: 'Viña del Mar', provincia_id: 14, region_id: 6 },
    { nombre: 'Isla de Pascua', provincia_id: 15, region_id: 6 },
    { nombre: 'Los Andes', provincia_id: 16, region_id: 6 },
    { nombre: 'Calle Larga', provincia_id: 16, region_id: 6 },
    { nombre: 'Rinconada', provincia_id: 16, region_id: 6 },
    { nombre: 'San Esteban', provincia_id: 16, region_id: 6 },
    { nombre: 'La Ligua', provincia_id: 17, region_id: 6 },
    { nombre: 'Cabildo', provincia_id: 17, region_id: 6 },
    { nombre: 'Papudo', provincia_id: 17, region_id: 6 },
    { nombre: 'Petorca', provincia_id: 17, region_id: 6 },
    { nombre: 'Zapallar', provincia_id: 17, region_id: 6 },
    { nombre: 'Quillota', provincia_id: 18, region_id: 6 },
    { nombre: 'Calera', provincia_id: 18, region_id: 6 },
    { nombre: 'Hijuelas', provincia_id: 18, region_id: 6 },
    { nombre: 'La Cruz', provincia_id: 18, region_id: 6 },
    { nombre: 'Nogales', provincia_id: 18, region_id: 6 },
    { nombre: 'San Antonio', provincia_id: 19, region_id: 6 },
    { nombre: 'Algarrobo', provincia_id: 19, region_id: 6 },
    { nombre: 'Cartagena', provincia_id: 19, region_id: 6 },
    { nombre: 'El Quisco', provincia_id: 19, region_id: 6 },
    { nombre: 'El Tabo', provincia_id: 19, region_id: 6 },
    { nombre: 'Santo Domingo', provincia_id: 19, region_id: 6 },
    { nombre: 'San Felipe', provincia_id: 20, region_id: 6 },
    { nombre: 'Catemu', provincia_id: 20, region_id: 6 },
    { nombre: 'Llaillay', provincia_id: 20, region_id: 6 },
    { nombre: 'Panquehue', provincia_id: 20, region_id: 6 },
    { nombre: 'Putaendo', provincia_id: 20, region_id: 6 },
    { nombre: 'Santa María', provincia_id: 20, region_id: 6 },
    { nombre: 'Quilpué', provincia_id: 21, region_id: 6 },
    { nombre: 'Limache', provincia_id: 21, region_id: 6 },
    { nombre: 'Olmué', provincia_id: 21, region_id: 6 },
    { nombre: 'Villa Alemana', provincia_id: 21, region_id: 6 },
  
    // Región Metropolitana de Santiago (RM)
    { nombre: 'Santiago', provincia_id: 22, region_id: 7 },
    { nombre: 'Cerrillos', provincia_id: 22, region_id: 7 },
    { nombre: 'Cerro Navia', provincia_id: 22, region_id: 7 },
    { nombre: 'Conchalí', provincia_id: 22, region_id: 7 },
    { nombre: 'El Bosque', provincia_id: 22, region_id: 7 },
    { nombre: 'Estación Central', provincia_id: 22, region_id: 7 },
    { nombre: 'Huechuraba', provincia_id: 22, region_id: 7 },
    { nombre: 'Independencia', provincia_id: 22, region_id: 7 },
    { nombre: 'La Cisterna', provincia_id: 22, region_id: 7 },
    { nombre: 'La Florida', provincia_id: 22, region_id: 7 },
    { nombre: 'La Granja', provincia_id: 22, region_id: 7 },
    { nombre: 'La Pintana', provincia_id: 22, region_id: 7 },
    { nombre: 'La Reina', provincia_id: 22, region_id: 7 },
    { nombre: 'Las Condes', provincia_id: 22, region_id: 7 },
    { nombre: 'Lo Barnechea', provincia_id: 22, region_id: 7 },
    { nombre: 'Lo Espejo', provincia_id: 22, region_id: 7 },
    { nombre: 'Lo Prado', provincia_id: 22, region_id: 7 },
    { nombre: 'Macul', provincia_id: 22, region_id: 7 },
    { nombre: 'Maipú', provincia_id: 22, region_id: 7 },
    { nombre: 'Ñuñoa', provincia_id: 22, region_id: 7 },
    { nombre: 'Pedro Aguirre Cerda', provincia_id: 22, region_id: 7 },
    { nombre: 'Peñalolén', provincia_id: 22, region_id: 7 },
    { nombre: 'Providencia', provincia_id: 22, region_id: 7 },
    { nombre: 'Pudahuel', provincia_id: 22, region_id: 7 },
    { nombre: 'Quilicura', provincia_id: 22, region_id: 7 },
    { nombre: 'Quinta Normal', provincia_id: 22, region_id: 7 },
    { nombre: 'Recoleta', provincia_id: 22, region_id: 7 },
    { nombre: 'Renca', provincia_id: 22, region_id: 7 },
    { nombre: 'San Joaquín', provincia_id: 22, region_id: 7 },
    { nombre: 'San Miguel', provincia_id: 22, region_id: 7 },
    { nombre: 'San Ramón', provincia_id: 22, region_id: 7 },
    { nombre: 'Vitacura', provincia_id: 22, region_id: 7 },
    { nombre: 'Puente Alto', provincia_id: 23, region_id: 7 },
    { nombre: 'Pirque', provincia_id: 23, region_id: 7 },
    { nombre: 'San José de Maipo', provincia_id: 23, region_id: 7 },
    { nombre: 'Colina', provincia_id: 24, region_id: 7 },
    { nombre: 'Lampa', provincia_id: 24, region_id: 7 },
    { nombre: 'Tiltil', provincia_id: 24, region_id: 7 },
    { nombre: 'San Bernardo', provincia_id: 25, region_id: 7 },
    { nombre: 'Buin', provincia_id: 25, region_id: 7 },
    { nombre: 'Calera de Tango', provincia_id: 25, region_id: 7 },
    { nombre: 'Paine', provincia_id: 25, region_id: 7 },
    { nombre: 'Melipilla', provincia_id: 26, region_id: 7 },
    { nombre: 'Alhué', provincia_id: 26, region_id: 7 },
    { nombre: 'Curacaví', provincia_id: 26, region_id: 7 },
    { nombre: 'María Pinto', provincia_id: 26, region_id: 7 },
    { nombre: 'San Pedro', provincia_id: 26, region_id: 7 },
    { nombre: 'Talagante', provincia_id: 27, region_id: 7 },
    { nombre: 'El Monte', provincia_id: 27, region_id: 7 },
    { nombre: 'Isla de Maipo', provincia_id: 27, region_id: 7 },
    { nombre: 'Padre Hurtado', provincia_id: 27, region_id: 7 },
    { nombre: 'Peñaflor', provincia_id: 27, region_id: 7 },
  
    // Región del Libertador General Bernardo O'Higgins (VI)
    { nombre: 'Rancagua', provincia_id: 28, region_id: 8 },
    { nombre: 'Codegua', provincia_id: 28, region_id: 8 },
    { nombre: 'Coinco', provincia_id: 28, region_id: 8 },
    { nombre: 'Coltauco', provincia_id: 28, region_id: 8 },
    { nombre: 'Doñihue', provincia_id: 28, region_id: 8 },
    { nombre: 'Graneros', provincia_id: 28, region_id: 8 },
    { nombre: 'Las Cabras', provincia_id: 28, region_id: 8 },
    { nombre: 'Machalí', provincia_id: 28, region_id: 8 },
    { nombre: 'Malloa', provincia_id: 28, region_id: 8 },
    { nombre: 'Mostazal', provincia_id: 28, region_id: 8 },
    { nombre: 'Olivar', provincia_id: 28, region_id: 8 },
    { nombre: 'Peumo', provincia_id: 28, region_id: 8 },
    { nombre: 'Pichidegua', provincia_id: 28, region_id: 8 },
    { nombre: 'Quinta de Tilcoco', provincia_id: 28, region_id: 8 },
    { nombre: 'Rengo', provincia_id: 28, region_id: 8 },
    { nombre: 'Requínoa', provincia_id: 28, region_id: 8 },
    { nombre: 'San Vicente', provincia_id: 28, region_id: 8 },
    { nombre: 'Pichilemu', provincia_id: 29, region_id: 8 },
    { nombre: 'La Estrella', provincia_id: 29, region_id: 8 },
    { nombre: 'Litueche', provincia_id: 29, region_id: 8 },
    { nombre: 'Marchihue', provincia_id: 29, region_id: 8 },
    { nombre: 'Navidad', provincia_id: 29, region_id: 8 },
    { nombre: 'Paredones', provincia_id: 29, region_id: 8 },
    { nombre: 'San Fernando', provincia_id: 30, region_id: 8 },
    { nombre: 'Chépica', provincia_id: 30, region_id: 8 },
    { nombre: 'Chimbarongo', provincia_id: 30, region_id: 8 },
    { nombre: 'Lolol', provincia_id: 30, region_id: 8 },
    { nombre: 'Nancagua', provincia_id: 30, region_id: 8 },
    { nombre: 'Palmilla', provincia_id: 30, region_id: 8 },
    { nombre: 'Peralillo', provincia_id: 30, region_id: 8 },
    { nombre: 'Placilla', provincia_id: 30, region_id: 8 },
    { nombre: 'Pumanque', provincia_id: 30, region_id: 8 },
    { nombre: 'Santa Cruz', provincia_id: 30, region_id: 8 },
  
    // Región del Maule (VII)
    { nombre: 'Talca', provincia_id: 31, region_id: 9 },
    { nombre: 'Constitución', provincia_id: 31, region_id: 9 },
    { nombre: 'Curepto', provincia_id: 31, region_id: 9 },
    { nombre: 'Empedrado', provincia_id: 31, region_id: 9 },
    { nombre: 'Maule', provincia_id: 31, region_id: 9 },
    { nombre: 'Pelarco', provincia_id: 31, region_id: 9 },
    { nombre: 'Pencahue', provincia_id: 31, region_id: 9 },
    { nombre: 'Río Claro', provincia_id: 31, region_id: 9 },
    { nombre: 'San Clemente', provincia_id: 31, region_id: 9 },
    { nombre: 'San Rafael', provincia_id: 31, region_id: 9 },
    { nombre: 'Cauquenes', provincia_id: 32, region_id: 9 },
    { nombre: 'Chanco', provincia_id: 32, region_id: 9 },
    { nombre: 'Pelluhue', provincia_id: 32, region_id: 9 },
    { nombre: 'Curicó', provincia_id: 33, region_id: 9 },
    { nombre: 'Hualañé', provincia_id: 33, region_id: 9 },
    { nombre: 'Licantén', provincia_id: 33, region_id: 9 },
    { nombre: 'Molina', provincia_id: 33, region_id: 9 },
    { nombre: 'Rauco', provincia_id: 33, region_id: 9 },
    { nombre: 'Romeral', provincia_id: 33, region_id: 9 },
    { nombre: 'Sagrada Familia', provincia_id: 33, region_id: 9 },
    { nombre: 'Teno', provincia_id: 33, region_id: 9 },
    { nombre: 'Vichuquén', provincia_id: 33, region_id: 9 },
    { nombre: 'Linares', provincia_id: 34, region_id: 9 },
    { nombre: 'Colbún', provincia_id: 34, region_id: 9 },
    { nombre: 'Longaví', provincia_id: 34, region_id: 9 },
    { nombre: 'Parral', provincia_id: 34, region_id: 9 },
    { nombre: 'Retiro', provincia_id: 34, region_id: 9 },
    { nombre: 'San Javier', provincia_id: 34, region_id: 9 },
    { nombre: 'Villa Alegre', provincia_id: 34, region_id: 9 },
    { nombre: 'Yerbas Buenas', provincia_id: 34, region_id: 9 },
  
    // Región de Ñuble (XVI)
    { nombre: 'Chillán', provincia_id: 35, region_id: 10 },
    { nombre: 'Bulnes', provincia_id: 35, region_id: 10 },
    { nombre: 'Cobquecura', provincia_id: 35, region_id: 10 },
    { nombre: 'Coelemu', provincia_id: 35, region_id: 10 },
    { nombre: 'Coihueco', provincia_id: 35, region_id: 10 },
    { nombre: 'Chillán Viejo', provincia_id: 35, region_id: 10 },
    { nombre: 'El Carmen', provincia_id: 35, region_id: 10 },
    { nombre: 'Ninhue', provincia_id: 35, region_id: 10 },
    { nombre: 'Ñiquén', provincia_id: 35, region_id: 10 },
    { nombre: 'Pemuco', provincia_id: 35, region_id: 10 },
    { nombre: 'Pinto', provincia_id: 35, region_id: 10 },
    { nombre: 'Portezuelo', provincia_id: 35, region_id: 10 },
    { nombre: 'Quillón', provincia_id: 35, region_id: 10 },
    { nombre: 'Quirihue', provincia_id: 35, region_id: 10 },
    { nombre: 'Ránquil', provincia_id: 35, region_id: 10 },
    { nombre: 'San Carlos', provincia_id: 35, region_id: 10 },
    { nombre: 'San Fabián', provincia_id: 35, region_id: 10 },
    { nombre: 'San Ignacio', provincia_id: 35, region_id: 10 },
    { nombre: 'San Nicolás', provincia_id: 35, region_id: 10 },
    { nombre: 'Treguaco', provincia_id: 35, region_id: 10 },
    { nombre: 'Yungay', provincia_id: 35, region_id: 10 },
  
    // Región del Biobío (VIII)
    { nombre: 'Concepción', provincia_id: 36, region_id: 11 },
    { nombre: 'Coronel', provincia_id: 36, region_id: 11 },
    { nombre: 'Chiguayante', provincia_id: 36, region_id: 11 },
    { nombre: 'Florida', provincia_id: 36, region_id: 11 },
    { nombre: 'Hualqui', provincia_id: 36, region_id: 11 },
    { nombre: 'Lota', provincia_id: 36, region_id: 11 },
    { nombre: 'Penco', provincia_id: 36, region_id: 11 },
    { nombre: 'San Pedro de la Paz', provincia_id: 36, region_id: 11 },
    { nombre: 'Santa Juana', provincia_id: 36, region_id: 11 },
    { nombre: 'Talcahuano', provincia_id: 36, region_id: 11 },
    { nombre: 'Tomé', provincia_id: 36, region_id: 11 },
    { nombre: 'Hualpén', provincia_id: 36, region_id: 11 },
    { nombre: 'Lebu', provincia_id: 37, region_id: 11 },
    { nombre: 'Arauco', provincia_id: 37, region_id: 11 },
    { nombre: 'Cañete', provincia_id: 37, region_id: 11 },
    { nombre: 'Contulmo', provincia_id: 37, region_id: 11 },
    { nombre: 'Curanilahue', provincia_id: 37, region_id: 11 },
    { nombre: 'Los Álamos', provincia_id: 37, region_id: 11 },
    { nombre: 'Tirúa', provincia_id: 37, region_id: 11 },
    { nombre: 'Los Ángeles', provincia_id: 38, region_id: 11 },
    { nombre: 'Antuco', provincia_id: 38, region_id: 11 },
    { nombre: 'Cabrero', provincia_id: 38, region_id: 11 },
    { nombre: 'Laja', provincia_id: 38, region_id: 11 },
    { nombre: 'Mulchén', provincia_id: 38, region_id: 11 },
    { nombre: 'Nacimiento', provincia_id: 38, region_id: 11 },
    { nombre: 'Negrete', provincia_id: 38, region_id: 11 },
    { nombre: 'Quilaco', provincia_id: 38, region_id: 11 },
    { nombre: 'Quilleco', provincia_id: 38, region_id: 11 },
    { nombre: 'San Rosendo', provincia_id: 38, region_id: 11 },
    { nombre: 'Santa Bárbara', provincia_id: 38, region_id: 11 },
    { nombre: 'Tucapel', provincia_id: 38, region_id: 11 },
    { nombre: 'Yumbel', provincia_id: 38, region_id: 11 },
    { nombre: 'Alto Biobío', provincia_id: 38, region_id: 11 },
  
    // Región de La Araucanía (IX)
    { nombre: 'Temuco', provincia_id: 39, region_id: 12 },
    { nombre: 'Carahue', provincia_id: 39, region_id: 12 },
    { nombre: 'Cunco', provincia_id: 39, region_id: 12 },
    { nombre: 'Curarrehue', provincia_id: 39, region_id: 12 },
    { nombre: 'Freire', provincia_id: 39, region_id: 12 },
    { nombre: 'Galvarino', provincia_id: 39, region_id: 12 },
    { nombre: 'Gorbea', provincia_id: 39, region_id: 12 },
    { nombre: 'Lautaro', provincia_id: 39, region_id: 12 },
    { nombre: 'Loncoche', provincia_id: 39, region_id: 12 },
    { nombre: 'Melipeuco', provincia_id: 39, region_id: 12 },
    { nombre: 'Nueva Imperial', provincia_id: 39, region_id: 12 },
    { nombre: 'Padre Las Casas', provincia_id: 39, region_id: 12 },
    { nombre: 'Perquenco', provincia_id: 39, region_id: 12 },
    { nombre: 'Pitrufquén', provincia_id: 39, region_id: 12 },
    { nombre: 'Pucón', provincia_id: 39, region_id: 12 },
    { nombre: 'Saavedra', provincia_id: 39, region_id: 12 },
    { nombre: 'Teodoro Schmidt', provincia_id: 39, region_id: 12 },
    { nombre: 'Toltén', provincia_id: 39, region_id: 12 },
    { nombre: 'Vilcún', provincia_id: 39, region_id: 12 },
    { nombre: 'Villarrica', provincia_id: 39, region_id: 12 },
    { nombre: 'Cholchol', provincia_id: 39, region_id: 12 },
    { nombre: 'Angol', provincia_id: 40, region_id: 12 },
    { nombre: 'Collipulli', provincia_id: 40, region_id: 12 },
    { nombre: 'Curacautín', provincia_id: 40, region_id: 12 },
    { nombre: 'Ercilla', provincia_id: 40, region_id: 12 },
    { nombre: 'Lonquimay', provincia_id: 40, region_id: 12 },
    { nombre: 'Los Sauces', provincia_id: 40, region_id: 12 },
    { nombre: 'Lumaco', provincia_id: 40, region_id: 12 },
    { nombre: 'Purén', provincia_id: 40, region_id: 12 },
    { nombre: 'Renaico', provincia_id: 40, region_id: 12 },
    { nombre: 'Traiguén', provincia_id: 40, region_id: 12 },
    { nombre: 'Victoria', provincia_id: 40, region_id: 12 },
  
    // Región de Los Ríos (XIV)
    { nombre: 'Valdivia', provincia_id: 41, region_id: 13 },
    { nombre: 'Corral', provincia_id: 41, region_id: 13 },
    { nombre: 'Lanco', provincia_id: 41, region_id: 13 },
    { nombre: 'Los Lagos', provincia_id: 41, region_id: 13 },
    { nombre: 'Máfil', provincia_id: 41, region_id: 13 },
    { nombre: 'Mariquina', provincia_id: 41, region_id: 13 },
    { nombre: 'Paillaco', provincia_id: 41, region_id: 13 },
    { nombre: 'Panguipulli', provincia_id: 41, region_id: 13 },
    { nombre: 'La Unión', provincia_id: 42, region_id: 13 },
    { nombre: 'Futrono', provincia_id: 42, region_id: 13 },
    { nombre: 'Lago Ranco', provincia_id: 42, region_id: 13 },
    { nombre: 'Río Bueno', provincia_id: 42, region_id: 13 },
  
    // Región de Los Lagos (X)
    { nombre: 'Puerto Montt', provincia_id: 43, region_id: 14 },
    { nombre: 'Calbuco', provincia_id: 43, region_id: 14 },
    { nombre: 'Cochamó', provincia_id: 43, region_id: 14 },
    { nombre: 'Fresia', provincia_id: 43, region_id: 14 },
    { nombre: 'Frutillar', provincia_id: 43, region_id: 14 },
    { nombre: 'Los Muermos', provincia_id: 43, region_id: 14 },
    { nombre: 'Llanquihue', provincia_id: 43, region_id: 14 },
    { nombre: 'Maullín', provincia_id: 43, region_id: 14 },
    { nombre: 'Puerto Varas', provincia_id: 43, region_id: 14 },
    { nombre: 'Castro', provincia_id: 44, region_id: 14 },
    { nombre: 'Ancud', provincia_id: 44, region_id: 14 },
    { nombre: 'Chonchi', provincia_id: 44, region_id: 14 },
    { nombre: 'Curaco de Vélez', provincia_id: 44, region_id: 14 },
    { nombre: 'Dalcahue', provincia_id: 44, region_id: 14 },
    { nombre: 'Puqueldón', provincia_id: 44, region_id: 14 },
    { nombre: 'Queilén', provincia_id: 44, region_id: 14 },
    { nombre: 'Quellón', provincia_id: 44, region_id: 14 },
    { nombre: 'Quemchi', provincia_id: 44, region_id: 14 },
    { nombre: 'Quinchao', provincia_id: 44, region_id: 14 },
    { nombre: 'Osorno', provincia_id: 45, region_id: 14 },
    { nombre: 'Puerto Octay', provincia_id: 45, region_id: 14 },
    { nombre: 'Purranque', provincia_id: 45, region_id: 14 },
    { nombre: 'Puyehue', provincia_id: 45, region_id: 14 },
    { nombre: 'Río Negro', provincia_id: 45, region_id: 14 },
    { nombre: 'San Juan de la Costa', provincia_id: 45, region_id: 14 },
    { nombre: 'San Pablo', provincia_id: 45, region_id: 14 },
    { nombre: 'Chaitén', provincia_id: 46, region_id: 14 },
    { nombre: 'Futaleufú', provincia_id: 46, region_id: 14 },
    { nombre: 'Hualaihué', provincia_id: 46, region_id: 14 },
    { nombre: 'Palena', provincia_id: 46, region_id: 14 },
  
    // Región de Aysén del General Carlos Ibáñez del Campo (XI)
    { nombre: 'Coyhaique', provincia_id: 47, region_id: 15 },
    { nombre: 'Lago Verde', provincia_id: 47, region_id: 15 },
    { nombre: 'Aysén', provincia_id: 48, region_id: 15 },
    { nombre: 'Cisnes', provincia_id: 48, region_id: 15 },
    { nombre: 'Guaitecas', provincia_id: 48, region_id: 15 },
    { nombre: 'Cochrane', provincia_id: 49, region_id: 15 },
    { nombre: 'O\'Higgins', provincia_id: 49, region_id: 15 },
    { nombre: 'Tortel', provincia_id: 49, region_id: 15 },
    { nombre: 'Chile Chico', provincia_id: 50, region_id: 15 },
    { nombre: 'Río Ibáñez', provincia_id: 50, region_id: 15 },
  
    // Región de Magallanes y de la Antártica Chilena (XII)
    { nombre: 'Punta Arenas', provincia_id: 51, region_id: 15 },
    { nombre: 'Laguna Blanca', provincia_id: 51, region_id: 15 },
    { nombre: 'Río Verde', provincia_id: 51, region_id: 15 },
    { nombre: 'San Gregorio', provincia_id: 51, region_id: 15 },
    { nombre: 'Cabo de Hornos', provincia_id: 52, region_id: 15 },
    { nombre: 'Antártica', provincia_id: 52, region_id: 15 },
    { nombre: 'Porvenir', provincia_id: 53, region_id: 15 },
    { nombre: 'Primavera', provincia_id: 53, region_id: 15 },
    { nombre: 'Natales', provincia_id: 54, region_id: 15 },
    { nombre: 'Torres del Paine', provincia_id: 54, region_id: 15 }
];

module.exports = { comunasChile };