apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
    - name: minio-alt
      port: 41935
      targetPort: 41935